### ISSUE TITLE
Unable to change the timeout when using mountService in ServletContextSyntax.scala

### ISSUE THREAD

**Issue by marcdanie** [http4s/http4s-servlet#12]
Comment from @rossabaker  
Oh, I see the problem
https://github.com/http4s/http4s/blob/master/servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala
We're setting the timeout there, but not passing it through as a param. That's bad design.

**Comment by valencik** [comment]
@rossabaker should this be closed as completed in https://github.com/http4s/http4s/pull/6037 ?

**Comment by rossabaker** [comment]
Yep!
