### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-servlet#3]
Proposed support matrix:

| http4s-servlet | http4s-core | Java | Servlet | Jetty | Tomcat |
|----------------|-------------|------|---------|-------|--------|
| 0.23.x         | 0.23.x      | 8    | 3.1     | 9.4.x | 9.0.x  |
| 0.24.x         | 0.23.x      | 11   | 4.0     | 10.x  | 9.0.x  |
| 0.25.x         | 0.23.x      | 11   | 5.0     | 11.x  | 10.0.x |
| 1.x            | 1.x         | 11   | 5.0     | 11.x  | 10.1.x |

Jetty 10 requires Java 11.  We don't _need_ to go to Java 11 in this repo until Servlet 6, but we'd have to replace Jetty in our tests.  The forthcoming http4s-jetty _will_ have to go 11.

Servlet 4 isn't really all that interesting, but keeping a minor version as a placeholder just in case seems prudent.  I could be talked into lazily materializing that branch.

I am not solving the problem of cross-building http4s versions for servlet versions.  I care deeply that we continue to support servlets it in some form, but there's not nearly enough demand to support it in cartesian product form.

**Comment by armanbilge** [comment]
Note that you can run CI in JDK 11+, and set `tlJdkRelease := Some(8)` or `tlJdkRelease := Some(11)` where appropriate. That is to say, you can ship artifacts for JDK 8 but run tests on JDK 11.

**Comment by rossabaker** [comment]
Oh, that's a good point, since it's a test-only dependency.  It still rubs me very much the wrong way to not test on what we publish for, but I guess that Java flag has gained a lot of credibility.  (I still have scars from the old "bootstrap" approach.)

**Comment by rossabaker** [comment]
We're proceeding with the above.
