### ISSUE TITLE
Evaluate update to Servlet 4 and Jetty 10

### ISSUE THREAD

**Issue by arixmkii** [http4s/http4s-servlet#9]
Current builds of Http4s are using Servlet 3.0 as build dependency. It would be nice to bump this to Servlet 4.0 before full move to `jakarta` namespaces and version 5.0.

Now it should be possible to bump Servlet version.
* Tomcat 9 implements Servlet 4.0 https://tomcat.apache.org/whichversion.html
* Jetty 10 also supports Servlet 4.0 https://www.eclipse.org/jetty/

Also, Jetty 10 kept `javax.servlet` namespace. So, upgrade should not be a breaking change at least for `jetty` server part.

If considered too dangerous the change could be skipped for `series/0.21`.

**Comment by rossabaker** [comment]
Servlet 4 support arrived on series/0.24.
